# Generated by Django 3.1.7 on 2021-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mApp', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
