# Generated by Django 3.1.7 on 2021-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mApp', '0004_auto_20210414_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
