# Generated by Django 3.1.7 on 2021-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mApp', '0005_auto_20210416_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='entry_year',
            field=models.IntegerField(null=True),
        ),
    ]
