# Generated by Django 3.1.7 on 2021-04-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mApp', '0007_auto_20210427_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.IntegerField(max_length=8, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mApp.post')),
            ],
        ),
    ]
