# Generated by Django 3.1.7 on 2021-05-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mApp', '0009_bid_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='offered_price',
            field=models.IntegerField(null=True),
        ),
    ]
