# Generated by Django 3.1.7 on 2021-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mApp', '0012_auto_20210518_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='exchange_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='exchange_book_author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='exchange_book_publisher',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='exchange_book_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
