# Generated by Django 3.1.7 on 2021-05-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mApp', '0012_auto_20210521_2305'),
        ('mApp', '0013_auto_20210520_1226'),
    ]

    operations = [
    ]
