# Generated by Django 3.2.4 on 2021-06-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mApp', '0014_merge_20210522_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
