# Generated by Django 3.2.4 on 2021-06-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mApp', '0015_auto_20210603_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_from_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='store_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
